excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

opt_in_rules:
  - force_unwrapping
 
line_length:
  warning: 160
  error: 250
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
  
disabled_rules:
  - function_body_length
  - nesting
warning_threshold: 50

cyclomatic_complexity:
  warning: 15
  ignores_case_statements: true

# forces are treated as errors
force_cast: error
force_try: error
force_unwrapping: error

type_name:
    min_length: 2
    max_length: 70

function_parameter_count:
    warning: 7
    error: 10

file_length:
    warning: 700
    error: 1000

identifier_name:                                                                                                           
    min_length:                                                                                                              
      error: 3                                                                                                               
    excluded:                                                                                                                
      - id                                                                                                                   
      - to
# custom rules
custom_rules:
   unnecessary_type:
      name: "Unnecessary Type"
      regex: '[ a-zA-Z0-9]*(?:let|var) [ a-zA-Z0-9]*: ([a-zA-Z0-9]*)[\? ]*= \1\('
      message: "Type Definition Not Needed"
      severity: error
